### ISSUE TITLE
Latest head driver doesn't compile on Ubuntu 13.04

### ISSUE THREAD

**Issue by usego** [stec-inc/EnhanceIO#50]
I've installed an Ubuntu 13.04 few weeks ago and successfully build EnhanceIO modules. Today I've noticed few segfaults and decided to build latest version. Now I'm getting the following on fresh clone:

root@DB1:/usr/src/EnhanceIO/Driver/enhanceio# make
make -C /lib/modules/3.8.0-19-generic/build M=/usr/src/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-19-generic'
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_conf.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_main.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_mem.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_policy.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.o
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c: In function ‘eio_stats_open’:
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1804:2: error: implicit declaration of function ‘PDE_DATA’ [-Werror=implicit-function-declaration]
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1804:2: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [enabled by default]
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio.h:54:0,
                 from /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:30:
include/linux/seq_file.h:125:5: note: expected ‘void *’ but argument is of type ‘int’
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c: In function ‘eio_errors_open’:
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1837:2: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [enabled by default]
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio.h:54:0,
                 from /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:30:
include/linux/seq_file.h:125:5: note: expected ‘void *’ but argument is of type ‘int’
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c: In function ‘eio_iosize_hist_open’:
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1872:2: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [enabled by default]
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio.h:54:0,
                 from /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:30:
include/linux/seq_file.h:125:5: note: expected ‘void *’ but argument is of type ‘int’
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c: In function ‘eio_version_open’:
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1894:2: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [enabled by default]
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio.h:54:0,
                 from /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:30:
include/linux/seq_file.h:125:5: note: expected ‘void *’ but argument is of type ‘int’
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c: In function ‘eio_config_open’:
/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:1931:2: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [enabled by default]
In file included from /usr/src/EnhanceIO/Driver/enhanceio/eio.h:54:0,
                 from /usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.c:30:
include/linux/seq_file.h:125:5: note: expected ‘void *’ but argument is of type ‘int’
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/EnhanceIO/Driver/enhanceio/eio_procfs.o] Error 1
make[1]: *** [_module_/usr/src/EnhanceIO/Driver/enhanceio] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.8.0-19-generic'
make: **\* [modules] Error 2
