### ISSUE TITLE
module does not compile on kernel 3.8.6

### ISSUE THREAD

**Issue by ghost** [stec-inc/EnhanceIO#44]
I get:

make -C /lib/modules/3.8.6/build M=/usr/src/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/linux-3.8.6'
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_conf.o
  CC [M]  /usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.o
/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.c: In function 'eio_ioctl':
/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.c:92:7: error: invalid application of 'sizeof' to incomplete type 'struct uint64_t' 
/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.c:92:7: error: array type has incomplete element type
/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.c:92:7: error: invalid application of 'sizeof' to incomplete type 'struct uint64_t' 
/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.c:92:7: error: invalid application of 'sizeof' to incomplete type 'struct uint64_t' 
make[2]: *** [/usr/src/EnhanceIO/Driver/enhanceio/eio_ioctl.o] Error 1
make[1]: *** [_module_/usr/src/EnhanceIO/Driver/enhanceio] Error 2
make[1]: Leaving directory`/usr/src/linux-3.8.6'
make: **\* [modules] Error 2
